spring.application.name=firesearchlogic

# Oracle
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

# JWT
jwt.secret=${JWT_SECRET}
jwt.issuer=${JWT_ISSUER}

# RabbitMQ
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}
spring.rabbitmq.virtual-host=${RABBITMQ_VHOST:/}

# Filas
rabbitmq.queue.firms=firms.foco-importado
rabbitmq.queue.iot=iot.sensor-leitura
rabbitmq.exchange=firesearch.exchange
rabbitmq.routing-key.firms=firms.risco
rabbitmq.routing-key.iot=iot.sensor

# firesearchIA
firesearch.ia.url=${FIRESEARCH_IA_URL:http://localhost:8001}

# FIRMS NASA
firms.api.key=${MAP_KEY}
firms.api.url=https://firms.modaps.eosdis.nasa.gov/api/area/csv/
firms.source=VIIRS_SNPP_NRT
firms.area=world
firms.day-range=1
